### ISSUE TITLE
Notification API change

### ISSUE THREAD

**Issue by mira-miracoli** [usegalaxy-eu/WallE#17]
I think there are now two issues with the `delete-user` functionality; with the Galaxy_API.notify_user method in particular.
1. the [json](https://github.com/usegalaxy-eu/WallE/blob/4cbd41a43628517c0f428ba8930a3c1fc066b0e5/files/walle.py#L817-L833) object seems to be faulty
2. this [check](https://github.com/usegalaxy-eu/WallE/blob/4cbd41a43628517c0f428ba8930a3c1fc066b0e5/files/walle.py#L836-L837) should be removed because Galaxy's API is giving back a celery task ID instead. Checking for `200` should be enough.

**Comment by davelopez** [comment]
> the [json](https://github.com/usegalaxy-eu/WallE/blob/4cbd41a43628517c0f428ba8930a3c1fc066b0e5/files/walle.py#L817-L833) object seems to be faulty

The JSON seems fine to me (given that `self.delete_subject` and `self.delete_message` contain a valid string). I would change the `source` to `walle`, though. The `source` parameter is an arbitrary string, but it is meant to identify "who" or "what" originated this notification.

**Comment by mira-miracoli** [comment]
yes thats true, I was just confused by the commas that black added, but it is a python dict I guess so that should be fine.

Thanks for the hint, I will add that :)
